development:
  adapter: postgresql
  database: rackit_development
  username: rackit
  encoding: unicode
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rackit_test
  username: rackit
  password:
  pool: 5
  timeout: 5000

# production:
#   adapter: postgresql
#   database: rackit_production
#   encoding: unicode
#   pool: 5
#   timeout: 5000
